In [3]:
import numpy as np

In [9]:
a = np.random.randint(1,10,[3,3])

In [10]:
a

array([[8, 1, 8],
       [4, 2, 7],
       [9, 8, 4]])

In [11]:
b = np.random.randint(1,10,[3,3])

In [12]:
b

array([[4, 3, 8],
       [3, 4, 3],
       [4, 3, 8]])

In [13]:
a+b

array([[12,  4, 16],
       [ 7,  6, 10],
       [13, 11, 12]])

In [14]:
a @ b

array([[ 67,  52, 131],
       [ 50,  41,  94],
       [ 76,  71, 128]])

In [15]:
a.T

array([[8, 4, 9],
       [1, 2, 8],
       [8, 7, 4]])

In [17]:
np.array([[1,2,3],[4,5,6]]).T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
s = "Sports in India refers to the large variety of games played in India, ranging from tribal games to more mainstream sports such as, cricket, football, field hockey, badminton and kabaddi"

In [36]:
l = s.lower()

In [39]:
words = l.split()
words.sort()

In [40]:
for i in words:
    print(i)


and
as,
badminton
cricket,
field
football,
from
games
games
hockey,
in
in
india
india,
kabaddi
large
mainstream
more
of
played
ranging
refers
sports
sports
such
the
to
to
tribal
variety
