In [1]:
import numpy as np

In [2]:
A = np.array([2,3,8,9,5])

In [3]:
sum = 0
for i in A:
    sum = sum + i
sum

27

In [4]:
B = np.array([42,12,33,3,43])

In [5]:
B

array([42, 12, 33,  3, 43])

In [6]:
c = 0
for i in B:
    if i > c:
        c = i
c

43

In [13]:
A = np.array([4,9,8,6,7])

In [14]:
for i in range(0,2):
    temp = A[0]
    for j in range(len(A)-1):
        A[j] = A[j+1]
    A[j] = temp
A    

array([8, 6, 4, 9, 7])

In [15]:
for i in range(0,2):
    temp = A[0]
    for j in range(len(A)-1):
        A[j] = A[j+1]
    A[j] = temp
A    

array([4, 9, 8, 6, 7])

In [47]:
z = np.array([1,2,3,4,5,6,7])

In [41]:
def ismonotonic(x):
    for i in range(len(x)-1):
        if x[i] <= x[i+1]:
            pass
        else:
            return False
    return True
ismonotonic(A)

False

In [43]:
A

array([4, 9, 8, 6, 7])

In [44]:
ismonotonic(B)

False

In [45]:
B

array([42, 12, 33,  3, 43])

In [48]:
z

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
ismonotonic(z)

True